TEXTS = {
    'uz': {
        'welcome': "🌟 **Xush kelibsiz {name}!**\n\nSizni botimizda ko'rib turganimizdan xursandmiz. Bu yerda siz o'zingizga yoqqan kinolarni faqat kodini yuborish orqali topishingiz mumkin.\n\n🎬 **Kino kodini yuboring:**",
        'enter_code': "🔢 Iltimos, videoning raqamli kodini yuboring:",
        'search_name': "🔎 Iltimos, qidirish uchun nom yoki sarlavhani yuboring:",
        'help': "📖 **Qanday foydalanish kerak:**\n1. Shunchaki kino kodini yuboring (masalan: 657)\n2. Sifatni tanlang\n3. Videoni qabul qiling!\n\nKunlik limit: 5 ta so'rov.",
        'invalid_code': "❌ Noto'g'ri kod. Iltimos, faqat raqam yuboring.",
        'limit_reached': "⚠️ Kunlik limit tugadi. Ertaga qayta urinib ko'ring.",
        'not_found': "❌ Kod topilmadi. Iltimos, tekshirib qayta urinib ko'ring.",
        'select_quality': "🎬 Video kodi: {code}\nSarlavha: {title}\n\nSifatni tanlang:",
        'video_sent': "✅ Video muvaffaqiyatli yuborildi.",
        'sub_required': "❌ Kechirasiz botimizdan foydalanishdan oldin ushbu kanallarga a'zo bo'lishingiz kerak.",
        'sub_check': "✅ Obuna bo'lganingiz uchun rahmat!",
        'sub_failed': "❌ Siz hali barcha kanallarga a'zo bo'lmagansiz yoki Instagram sahifamizga kirmagansiz.",
        'search_results': "🔎 **Qidiruv natijalari:**\n\n{results}\n\nVideoni olish uchun kodni yuboring.",
        'no_results': "❌ Bu nomga mos videolar topilmadi.",
        'btn_enter_code': "🎬 Kodni kiritish",
        'btn_search_name': "🔎 Nomi bo'yicha qidirish",
        'btn_help': "📜 Yordam",
        'btn_sub': "{n} - kanal",
        'btn_check_sub': "✅ Tasdiqlash",
        'lang_selected': "🇺🇿 O'zbek tili tanlandi."
    },
    'uz_cyr': {
        'welcome': "🌟 **Хуш келибсиз!**\n\nСизни ботимизда кўриб турганимиздан хурсандмиз. Бу ерда сиз ўзингизга ёққан киноларни фақат кодини юбориш орқали топишингиз мумкин.\n\n🎬 **Кино кодини юборинг:**",
        'enter_code': "🔢 Илтимос, видеонинг рақаmli кодини юборинг:",
        'search_name': "🔎 Илтимос, қидириш учун ном ёки сарлавҳани юборинг:",
        'help': "📖 **Қандай фойдаланиш керак:**\n1. Шунчаки кино кодини юборинг (масалан: 657)\n2. Сифатни танланг\n3. Видеони қабул қилинг!\n\nКунлик лимит: 5 та сўров.",
        'invalid_code': "❌ Нотўғри код. Илтимос, фақат рақам юборинг.",
        'limit_reached': "⚠️ Кунлик лимит тугади. Эртага қайта уриниб кўринг.",
        'not_found': "❌ Код топилмади. Илтимос, текшириб қайта уриниб кўринг.",
        'select_quality': "🎬 Видео коди: {code}\nСарлавҳа: {title}\n\nСифатни танланг:",
        'video_sent': "✅ Видео муваффақиятли юборилди.",
        'sub_required': "❌ Кечирасиз ботимиздан фойдаланишдан олдин ушбу каналларга аъзо бўлишингиз керак.",
        'sub_check': "✅ Обуна бўлганингиз учун раҳмат!",
        'sub_failed': "❌ Сиз ҳали барча каналларга обуна бўлмагансиз.",
        'search_results': "🔎 **Қидирув натижалари:**\n\n{results}\n\nВидеони олиш учун кодни юборинг.",
        'no_results': "❌ Бу номга мос видеолар топилмади.",
        'btn_enter_code': "🎬 Кодни киритиш",
        'btn_search_name': "🔎 Номи бўйича қидириш",
        'btn_help': "📜 Ёрдам",
        'btn_sub': "{n} - канал",
        'btn_check_sub': "✅ Тасдиқлаш",
        'lang_selected': "🇺🇿 Ўзбек тили танланди."
    },
    'ru': {
        'welcome': "🌟 **Добро пожаловать!**\n\nРады видеть вас в нашем боте. Здесь вы можете найти свои любимые фильмы, просто отправив код.\n\n🎬 **Отправьте код фильма:**",
        'enter_code': "🔢 Пожалуйста, отправьте цифровой код видео:",
        'search_name': "🔎 Пожалуйста, отправьте название для поиска:",
        'help': "📖 **Как использовать:**\n1. Просто отправьте код фильма (напр.: 657)\n2. Выберите качество\n3. Получите ваше видео!\n\nДневной лимит: 5 запросов.",
        'invalid_code': "❌ Неверный код. Пожалуйста, присылайте только цифры.",
        'limit_reached': "⚠️ Дневной лимит исчерпан. Попробуйте завтра.",
        'not_found': "❌ Код не найден. Пожалуйста, проверьте и попробуйте еще раз.",
        'select_quality': "🎬 Код видео: {code}\nЗаголовок: {title}\n\nВыберите качество:",
        'video_sent': "✅ Видео успешно отправлено.",
        'sub_required': "❌ Извините, вы должны быть подписаны на эти каналы, прежде чем использовать нашего бота.",
        'sub_check': "✅ Спасибо за подписку!",
        'sub_failed': "❌ Вы еще не подписаны на все каналы.",
        'search_results': "🔎 **Результаты поиска:**\n\n{results}\n\nОтправьте код, чтобы получить видео.",
        'no_results': "❌ Видео с таким названием не найдено.",
        'btn_enter_code': "🎬 Ввести код",
        'btn_search_name': "🔎 Поиск по названию",
        'btn_help': "📜 Помощь",
        'btn_sub': "{n} - канал",
        'btn_check_sub': "✅ Подтвердить",
        'lang_selected': "🇷🇺 Выбран русский язык."
    },
    'en': {
        'welcome': "🌟 **Welcome!**\n\nWe are glad to see you in our bot. Here you can find your favorite movies just by sending the code.\n\n🎬 **Send the movie code:**",
        'enter_code': "🔢 Please send the numeric code of the video:",
        'search_name': "🔎 Please send the name or title to search:",
        'help': "📖 **How to use:**\n1. Just send the movie code (e.g. 657)\n2. Choose quality\n3. Receive your video!\n\nDaily limit: 5 requests.",
        'invalid_code': "❌ Invalid code. Please send numbers only.",
        'limit_reached': "⚠️ Daily limit reached. Try again tomorrow.",
        'not_found': "❌ Code not found. Please check and try again.",
        'select_quality': "🎬 Video Code: {code}\nTitle: {title}\n\nSelect quality:",
        'video_sent': "✅ Video sent successfully.",
        'sub_required': "❌ Sorry, you must be subscribed to these channels before using our bot.",
        'sub_check': "✅ Thank you for subscribing!",
        'sub_failed': "❌ You are still not subscribed to all channels.",
        'search_results': "🔎 **Search Results:**\n\n{results}\n\nSend the code to get the video.",
        'no_results': "❌ No videos found matching that name.",
        'btn_enter_code': "🎬 Enter Code",
        'btn_search_name': "🔎 Search by Name",
        'btn_help': "📜 Help",
        'btn_sub': "{n} - channel",
        'btn_check_sub': "✅ Confirm",
        'lang_selected': "🇺🇸 English language selected."
    }
}
